In [1]:
import tensorflow as tf
print(tf.version)

E:\Softwares\Anaconda\envs\nlp\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
E:\Softwares\Anaconda\envs\nlp\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
E:\Softwares\Anaconda\envs\nlp\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


<module 'tensorflow._api.v2.version' from 'C:\\Users\\sayan\\AppData\\Roaming\\Python\\Python37\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [2]:
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
x = tf.zeros(shape=(1,2))
print(x)

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [8]:
# Random tensors
x = tf.random.normal(shape=(3,1), mean=0., stddev=1.) #Tensor of random values drawn from a normal distribution
print(x)
x = tf.random.uniform(shape=(3,1), minval=0., maxval=1.) # Tensor of random values drawn from a uniform distribution between 0 and 1
print(x)

tf.Tensor(
[[-0.2773562 ]
 [-0.18953896]
 [ 0.25179994]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.88938093]
 [0.78508294]
 [0.24940479]], shape=(3, 1), dtype=float32)


In [9]:
# Tensor-Flow tensors aren’t assignable: they’re constant
x = tf.ones(shape=(2, 2))
x[0, 0] = 0. ## This will throw an error

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [18]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.43784028],
       [ 0.04725995],
       [-1.725765  ]], dtype=float32)>


In [19]:
# This can be reassigned as its of variable class but the shape must be the same
v.assign(tf.ones(shape=(3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [20]:
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [21]:
# Similarly, assign_add() and assign_sub() are efficient equivalents of += and -=
v.assign_add(2*tf.ones(shape=(3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[5.],
       [3.],
       [3.]], dtype=float32)>

In [22]:
# Using the GradientTape to retrieve the gradient of the result with respect to the inputs
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [27]:
# Using GradientTape with constant tensor inputs
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    res = tf.square(input_const)
grad = tape.gradient(res, input_const)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)
