In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'E:\\Softwares\\Anaconda\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


## Refer to [this notebook](https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true)

In [2]:
string = tf.Variable("This is a string", tf.string)
num = tf.Variable(324, tf.int16)
float_num = tf.Variable(3.567, tf.float64)

In [3]:
rank1_tensor = tf.Variable(["Test"], tf.string)

In [4]:
rank2_tensor = tf.Variable([["Test", "fine"], ["Tim", "ok"]], tf.string)

In [6]:
ragged_tensor = tf.ragged.constant([["Test"], ["fine", "tim"]])

In [7]:
tf.rank(ragged_tensor) #numpy=2 means rank 2 tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

In [10]:
rank3_tensor.shape

TensorShape([2, None])

In [11]:
tensor1 = tf.ones([1,2,3])

In [12]:
tensor1.shape

TensorShape([1, 2, 3])

In [13]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [14]:
tensor2 = tf.reshape(tensor1,[2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [16]:
tensor3 = tf.reshape(tensor2, [3,-1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [22]:
t = tf.zeros([5,5,5,5])
print(tf.rank(t))

tf.Tensor(4, shape=(), dtype=int32)


In [26]:
t2 = tf.reshape(t, [625])
tf.print(t2)

[0 0 0 ... 0 0 0]


In [27]:
t3 = tf.reshape(t, [125,-1])
tf.print(t3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 ...
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20],
          [21,22,23,24,25],
          [26,27,28,29,30]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(6, 5)


In [17]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[0::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16 21 26], shape=(6,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]], shape=(3, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
